//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mine
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Origin { get; set; }
    }
}
